### ISSUE TITLE
decoder not composable

### ISSUE THREAD

**Issue by doofin** [abdolence/circe-tagged-adt-codec#2]
```scala
  object bug {
    import io.circe.parser._
    import io.circe.syntax._
    import org.latestbit.circe.adt.codec._

    case class Cls(a: Int = 0)
    implicit val e = JsonTaggedAdtCodec.createEncoder[Cls]("tp")
    implicit val d = JsonTaggedAdtCodec.createDecoder[Cls]("tp")
    def test = {
      val r = decode[Seq[Cls]](Seq(Cls()).asJson.toString())
      println(r)
    }
  }
```

This will give out `Left(DecodingFailure('tp' isn't specified in json., List(DownArray)))`

**Comment by abdolence** [comment]
It is interesting seeing usage with just one class without trait at all (I probably missed the check and didn't even know this is available to be used), but anyhow it seems working for me:
I put an additional test to be sure:
https://github.com/abdolence/circe-tagged-adt-codec/blob/d05abf1deac4fbdbaa9b5ec619273de5c0743f7f/lib/shared/src/test/scala/org/latestbit/circe/adt/codec/tests/JsonTaggedAdtCodecImplTestSuite.scala#L519

Can you make this test fail? Because I made it from your code right now.

**Comment by abdolence** [comment]
I even tried to create a sepated source file with
```
package org.latestbit.circe.adt.codec

object bug extends App {
  import io.circe.parser._
  import io.circe.syntax._
  import org.latestbit.circe.adt.codec._

  case class Cls(a: Int = 0)
  implicit val e = JsonTaggedAdtCodec.createEncoder[Cls]("tp")
  implicit val d = JsonTaggedAdtCodec.createDecoder[Cls]("tp")
  def test() = {
    val r = decode[Seq[Cls]](Seq(Cls()).asJson.toString())
    println(r)
  }

  test()
}
```
with exactly the same code you gave me, and it produces me:
```
Right(List(Cls(0)))
```

so probably there is something different related to versions, imports or environment.

**Comment by doofin** [comment]
Thanks! I have move the code to other places and it worked as expected.The bug is quite strange,maybe due to imports or implicits in circe/scalajs


my setup: 

scala : "2.13.3"
scala js : 1.3.1

**Comment by doofin** [comment]
oh,it's a bug with scala js 1.3.1
https://github.com/circe/circe/issues/1620

**Comment by abdolence** [comment]
interesting behaviour indeed, thanks for posting
